### PR TITLE
Adding the ability to specify a custom Chocolatey Repo

### PR DESCRIPTION
**Pull request by smadam813**
I tested this with my local chocolatey repo and it works great!  Please review and let me know if you like the approach.  PS: Sorry I am new to the Git workflow so I may have some unnecessary commits.

### CODE REVIEW

**Comment by elventear** [comment]
@ferventcoder could you give some feedback about using custom repos with chocolatey? This is to address your comments in https://github.com/ansible/ansible-modules-extras/pull/398 regarding https://github.com/chocolatey/choco/issues/14.

**Comment by smadam813** [comment]
Another way we could do this is just have chocolatey still be the source then have an optional url parameter than overrides the default.  (alternative to what I did, but accomplishes the same thing)

**Comment by ferventcoder** [comment]
Alternative sources - 
- Ruby
- Windows Features
- WebPI

Alternative sources are missing from 0.9.9.x but will be back in 0.9.10. We expected to have 0.9.10 functional by now, but schedules and all of that other fun stuff in stabilizing the new platform has been fun. :/ 

The other is using other Nuget compliant sources other than the community feed, like CIFS, local folders, and OData feeds, those all work. Those are where this idea of custom private sources comes in.

**Comment by ferventcoder** [comment]
I would probably let choco determine if the source is usable or not. 

> Another way we could do this is just have chocolatey still be the source then have an optional url parameter than overrides the default. (alternative to what I did, but accomplishes the same thing)

If you explicitly specify the source it overrides any custom sources the user has set into choco as well (which may be behind a user/password). I would only override/pass `-source` if the user explicitly provides it.

**Comment by smadam813** [comment]
@ferventcoder  OK I think I know what you are suggesting.  How about something like this:

```
  source:
    description:
      - Specify source rather than using default chocolatey repository
    require: false
    default: null
    aliases: []
```

To be honest, I never saw the point of specifying a source such as webpi or windowsfeature when you could have much more customization to just specify the URL.  I can figure something out for optional passing of credentials if authentication is required.

I would then adjust the script to never use -source unless this field != null.

How does this sound?

**Comment by ferventcoder** [comment]
@smadam813 sounds good. :)

**Comment by smadam813** [comment]
@ferventcoder I removed the pre-determined sources and added the ability to specify a source url.  If no source is specified, "-source" is left out of the command line.  If you specify an incorrect url, chocolatey properly reports the error and fails with the error "The package was not found with the source(s) listed.".  I think the logic for sources such as webPI etc should be captured outside of this module.

**Comment by bcoca** [comment]
can you rebase this request?

**Comment by smadam813** [comment]
@bcoca Is this something I can do, or does @elventear need to do this since I have a pull request into his branch?  Sorry new to git workflow.

**Pull request merged**
